### ISSUE TITLE
Escape characters in strings

### ISSUE THREAD

**Issue by dev1050** [blacktop/language-yara#2]
Hey, 

Great module, very useful. I've noticed that using '\' to escape characters in a string was not being recognized. It looks like the code references '#string_escaped_char' without defining it. Copying in a definition from c.cson (https://github.com/atom/language-c/blob/master/grammars/c.cson) fixed the issue in my local copy.

Kind regards

**Comment by blacktop** [comment]
Does this fix the issue?

**Comment by dev1050** [comment]
Yep that fixed it. 
Thanks
